name: pickle_compression
channels:
  - conda-forge
  - nodefaults
dependencies:
  - lightgbm
  - numpy
  - python>=3.8
  - pre-commit
  - pandas
  - scikit-learn
  - pytest
  - setuptools_scm
  - tbump
