# use pixi.toml instead!
name: slim_trees
channels:
  - conda-forge
  - nodefaults
dependencies:
  - lightgbm >=3.2,<4.1
  - numpy
  - python>=3.8
  - pre-commit
  - pandas
  - scikit-learn <1.3.0
  - pytest>=7.0
  - hatchling
