[project] # TODO: move to pyproject.toml once pixi supports it
name = "slim-trees"
description = "A python package for efficient pickling of ML models."
channels = ["conda-forge"]
platforms = ["osx-arm64", "osx-64", "linux-64", "linux-aarch64", "win-64"]

[tasks]
postinstall = "pip install --no-build-isolation --no-deps --disable-pip-version-check -e ."

[dependencies]
python = ">=3.8"
numpy = ">=1,<3"

[host-dependencies]
pip = "*"
hatchling = "*"

[feature.test.dependencies]
lightgbm = ">=3.2,<4.4"
scikit-learn = ">=1.1,<1.6"
pytest = ">=7.0"
pytest-md = "*"
pytest-emoji = "*"
pandas = "*"
mypy = "*"
pandas-stubs = "*"
[feature.test.tasks]
test = "pytest"

[feature.lgbm32.dependencies]
lightgbm = ">=3.2,<3.3"
[feature.lgbm33.dependencies]
lightgbm = ">=3.3,<3.4"
[feature.lgbm40.dependencies]
lightgbm = ">=4.0,<4.1"
[feature.lgbm41.dependencies]
lightgbm = ">=4.1,<4.2"
[feature.lgbm42.dependencies]
lightgbm = ">=4.2,<4.3"
[feature.lgbm43.dependencies]
lightgbm = ">=4.3,<4.4"
[feature.skl11.dependencies]
scikit-learn = ">=1.1,<1.2"
[feature.skl12.dependencies]
scikit-learn = ">=1.2,<1.3"
[feature.skl13.dependencies]
scikit-learn = ">=1.3,<1.4"
[feature.skl14.dependencies]
scikit-learn = ">=1.4,<1.5"
[feature.skl15.dependencies]
scikit-learn = ">=1.5,<1.6"
[feature.np1.dependencies]
numpy = "1.*"
[feature.np2.dependencies]
numpy = "2.*"
[feature.py38.dependencies]
python = ">=3.8,<3.9"
[feature.py39.dependencies]
python = ">=3.9,<3.10"
[feature.py310.dependencies]
python = ">=3.10,<3.11"
[feature.py311.dependencies]
python = ">=3.11,<3.12"
[feature.py312.dependencies]
python = ">=3.12,<3.13"

[feature.lint.dependencies]
pre-commit = "*"
ruff = "*"
pre-commit-hooks = "*"
typos = "*"
[feature.lint.tasks]
pre-commit-install = "pre-commit install"
pre-commit-run = "pre-commit run -a"

[environments]
default = ["test"]
skl11 = ["py38", "skl11", "test", "np1"]
skl12 = ["py38", "skl12", "test", "np1"]
skl13 = ["py38", "skl13", "test", "np1"]
skl14 = ["py39", "skl14", "test", "np1"]
skl15 = ["py39", "skl15", "test", "np2"]
lgbm32 = ["py38", "lgbm32", "test", "np1"]
lgbm33 = ["py38", "lgbm33", "test", "np1"]
lgbm40 = ["py38", "lgbm40", "test", "np1"]
lgbm41 = ["py38", "lgbm41", "test", "np1"]
lgbm42 = ["py38", "lgbm42", "test", "np1"]
lgbm43 = ["py38", "lgbm43", "test", "np1"]
py38 = ["py38", "test", "np1"]
py39 = ["py39", "test", "np1"]
py310 = ["py310", "test", "np1"]
py311 = ["py311", "test", "np1"]
py312 = ["py312", "test", "np2"]
lint = { features = ["lint"], no-default-feature = true }
