[project] # TODO: move to pyproject.toml once pixi supports it
name = "slim-trees"
version = "0.2.4"
description = "A python package for efficient pickling of ML models."
authors = ["Pavel Zwerschke <pavelzw@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64", "osx-64", "linux-64", "linux-aarch64", "linux-ppc64le", "win-64"]

[tasks]
postinstall = "pip install --no-build-isolation --no-deps --disable-pip-version-check -e ."
test = "pytest"
lint = "pre-commit run -a"

[dependencies]
python = ">=3.8"
pip = "*"
lightgbm = ">=3.2,<4.1"
numpy = "*"
pre-commit = "*"
pandas = "*"
scikit-learn = ">=1.1.0,<1.4"
hatch = "*"
pytest = ">=7.0"
pytest-md = "*"
pytest-emoji = "*"
